<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P6F1DDQ" failures="1" tests="3" name="Test" time="0.101" errors="0" timestamp="2024-09-06T18:22:15 IST">
  <testcase classname="testng.ListnerTest" name="test1" time="0.018"/>
  <testcase classname="testng.ListnerTest" name="test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testng.ListnerTest.test2(ListnerTest.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testng.ListnerTest" name="test3" time="0.0">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
